live_config_reload: true

window:
  dynamic_padding: false
  dynamic_title: true
  padding:
    y: 2
    x: 2


font:
  # No idea what's the deal with font size
  size: 5.0
  normal:
    family: Fira Mono
  offset:
    x: 0


cursor:
  style:
    shape: block
    blinking: on
    unfocussed_hollow: true

mouse:
  url:
    launcher:
      program: xdg-open


# Run "$ alacritty --print-events | grep Key"
# to find scancodes if a name is missing.
#
# for names of (some) of them
# https://docs.rs/glutin/0.26.0/glutin/event/enum.VirtualKeyCode.html
key_bindings:
  - { key: Escape,                mode: Vi|~Search, action: ToggleViMode }
  - { key: G,      mods: Control, mode: Vi|~Search, action: ToggleViMode }
  - { key: Q,                     mode: Vi|~Search, action: ToggleViMode }
  - { key: G,      mods: Control, mode: Search,     action: SearchCancel }
  - { key: 22,                    mode: Vi|~Search, action: SearchBackward } # ?
  - { key: 36,                    mode: Vi|~Search, action: First } # ^
  - { key: 20,                    mode: Vi|~Search, action: Last  } # $


import:
  # Sets default colors
  - ~/.config/alacritty/color.yml
  # override them with day/night specific if present
  - ~/.config/daynight/alacritty.yml
