colors:
  primary:
    background: '#1d1f21'
    foreground: '#c5c8c6'

  normal:
    black:         '#1d1f21'
    red:           '#a54242'
    green:         '#8c9440'
    yellow:        '#de935f'
    # shifted saturation from 39 to 70
    #blue:         '#5f819d'
    blue:          '#2f6c9e'
    magenta:       '#85678f'
    # cyan: H 174, S 45, V 55
    cyan:          '#5e8d87'
    white:         '#c5c8c6'

  # dim left unset to get automatically dimmed normal colors

  # Alacrittys default normal colors
  # but coincidentally almost my exact bright colors
  # (excluding black)
  bright:
    black:   '#959992'
    red:     '#cc6666'
    green:   '#b5bd68'
    yellow:  '#f0c674'
    blue:    '#81a2be'
    magenta: '#b294bb'
    cyan:    '#8abeb7'
    white:   '#c5c8c6'
