[colors.primary]
background = "#f7f7f7"
foreground = "#4a4543"

[colors.normal]
black   = "#090300"
blue    = "#01a0e4"
cyan    = "#b5e4f4"
green   = "#01a252"
magenta = "#a16a94"
red     = "#db2d20"
white   = "#a5a2a2"
# The actual yellow of this colorscheme is #fded02, but it's unreadable. 
yellow  = "#f59700"

[colors.bright]
black   = "#5c5855"
blue    = "#01a0e4"
cyan    = "#b5e4f4"
green   = "#01a252"
magenta = "#a16a94"
red     = "#db2d20"
white   = "#f7f7f7"
yellow  = "#fded02"
