#!/bin/bash

. $(dirname $(dirname $(realpath $0)))/common

case $1 in
	dawn) theme=light ;;
	dusk) theme=dark ;;
esac

alacritty="$CONF/alacritty/daynight.toml"
rm $alacritty
ln -s "$CONF/alacritty/${theme}.toml" $alacritty
# force reload
touch "$(dirname $alacritty)/alacritty.toml"
