#!/bin/bash

path="$(dirname "$(realpath "$0")")"
ln -s "$path/bashrc"            ~/.bashrc
ln -s "$path/gitconfig"         ~/.gitconfig
ln -s "$path/gitignore_global"  ~/.gitignore_global
ln -s "$path/inputrc"           ~/.inputrc
ln -s "$path/lynxrc"            ~/.lynxrc
ln -s "$path/tmux.conf"         ~/.tmux.conf
ln -s "$path/vimrc"             ~/.vimrc
ln -s "$path/bash_aliases"      ~/.bash_aliases
ln -s "$path/bash_profile"      ~/.bash_profile
ln -s "$path/xinitrc"           ~/.xinitrc
ln -s "$path/xmonad/"           ~/.xmonad
ln -s "$path/Xresources"        ~/.Xresources

ELINK_DIR="~/.elinks"
if [ -d "`eval echo ${ELINK_DIR//>}`" ]; then
	ln -s "$path/elinks.conf" ~/.elinks/elinks.conf
fi
