#!/bin/bash

path="$(dirname "$(realpath "$0")")"
ln -s "$path/bashrc"            ~/.bashrc
ln -s "$path/gitconfig"         ~/.gitconfig
ln -s "$path/gitignore_global"  ~/.gitignore_global
ln -s "$path/inputrc"           ~/.inputrc
ln -s "$path/tmux.conf"         ~/.tmux.conf
ln -s "$path/vimrc"             ~/.vimrc
ln -s "$path/gvimrc"            ~/.gvimrc
ln -s "$path/bash_aliases"      ~/.bash_aliases
ln -s "$path/bash_profile"      ~/.bash_profile
ln -s "$path/xinitrc"           ~/.xinitrc
ln -s "$path/xmonad"            ~/.xmonad # This currently creates a recursize symilnk
ln -s "$path/Xresources"        ~/.Xresources
ln -s "$path/start_tmux"        ~/.start_tmux
ln -s "$path/kill_window"       ~/bin/texit
ln -s "$path/dmenu_info_bar"    ~/bin/dmenu_info_bar
ln -s "$path/tmux.extra.conf"   ~/.tmux.extra.conf
ln -s "$path/i3-config"         ~/.config/i3/config # the i3 dir might not be there

#ln -s "$path/termite-config"    ~/.config/termite/config
ln -s "$path/termite" ~/.termite
ln -s "$path/vim" ~/.vim

if [ -n "~/bin" ]; then
	ln -s "$path/start-termite" ~/bin/start-termite
else
	echo "no bin directory"
fi

[ ! -b ~/.config/i3status ] && mkdir ~/.config/i3status
tput bold
echo "YOU HAVE TO SYMLING THE I3 STATUS YOUSELF!"
echo "it should be in ~/.config/i3status/config"
tput sgr0

ELINK_DIR="~/.elinks"
if [ -d "`eval echo ${ELINK_DIR//>}`" ]; then
	ln -s "$path/elinks.conf" ~/.elinks/elinks.conf
fi
