#!/bin/bash

# allows for dynamic choosing of termite colorschemes

curColor="default"
curOther="default"

if [ "$(hostname)" == "arch2012" ]; then
	curOther="archdesktop"
fi
if [ "$(hostname)" == "HPlinux" ]; then
	curOther="laptop"
fi

if [ "$1" == "large" ]; then
	curOther="large"
elif [ "$1" == "1337" ]; then
	curColor="1337"
elif [ "$1" == "test" ]; then
	curColor="test"
fi

curColor="$HOME/.termite/selectorFiles/color/$curColor";
curOther="$HOME/.termite/selectorFiles/other/$curOther";

rm "$HOME/.termite/generated.conf"
for x in $(cat $curColor $curOther); do
	cat "$HOME/.termite/$x" >> "$HOME/.termite/generated.conf"
done
termite -c "$HOME/.termite/generated.conf"
