" Set's up GVim as a small floating terminal,
" The floating part should be handled by the window manager 

set lines=24 columns=80
" disables all silly gui stuff
set guioptions-=m
set guioptions-=T
set guioptions-=r
set guioptions-=L

set nonumber
set laststatus=0

set novisualbell

set noruler
set noshowcmd
set statusline=""
set guifont=Fira\ Mono\ 10

" colorscheme darkblue
colorscheme delek

" https://www.reddit.com/r/vim/comments/k7w0gy/a_simple_function_for_zooming_in_gui_version_of/
" Increases the font size with `amount`
function! Zoom(amount) abort
  call ZoomSet(matchstr(&guifont, '\d\+$') + a:amount)
endfunc

" Sets the font size to `font_size`
function ZoomSet(font_size) abort
  let &guifont = substitute(&guifont, '\d\+$', a:font_size, '')
endfunc

noremap <silent> <C-+> :call Zoom(v:count1)<CR>
noremap <silent> <C--> :call Zoom(-v:count1)<CR>
" No idea why C-- gives C-_, but eh.
noremap <silent> <C-_> :call Zoom(-v:count1)<CR>
noremap <silent> <C-0> :call ZoomSet(11)<CR>
