" Set's up GVim as a small floating terminal,
" The floating part should be handled by the window manager 

set lines=24 columns=80
" disables all silly gui stuff
set guioptions-=m
set guioptions-=T
set guioptions-=r
set guioptions-=L

set nonumber
set laststatus=0

set novisualbell

set noruler
set noshowcmd
set statusline=""
set guifont=Fira\ Mono\ 10

" colorscheme darkblue
colorscheme delek

" TODO if the window is changed to quickly after opening gvim then than window
" might become transparent instead
"
" Make the Gui Window semi transparent.
" This should preferably be changed so it's set in the wm settings
autocmd GUIEnter    * silent exec "!transset-df -a 0.9"
"autocmd FocusLost   * exec "!transset-df -n "GVIM$" 0.5"
"autocmd FocusGained * exec "!transset-df -a 0.9"

" https://new.reddit.com/r/vim/comments/k7w0gy/a_simple_function_for_zooming_in_gui_version_of/ {{{
" Increases the font size with `amount`
function! Zoom(amount) abort
  call ZoomSet(matchstr(&guifont, '\d\+$') + a:amount)
endfunc

" Sets the font size to `font_size`
function ZoomSet(font_size) abort
  let &guifont = substitute(&guifont, '\d\+$', a:font_size, '')
endfunc

noremap <silent> <C-+> :call Zoom(v:count1)<CR>
noremap <silent> <C--> :call Zoom(-v:count1)<CR>
" No idea why C-- gives C-_, but eh.
noremap <silent> <C-_> :call Zoom(-v:count1)<CR>
noremap <silent> <C-0> :call ZoomSet(11)<CR>
" }}}
