#!/bin/bash

CONF="${XDG_CONFIG_HOME:-$HOME/.config}/termite"

day_theme=baskerville-ivorylight
night_theme=fira-mono-8

relink_termite() {
	theme="$1"
	path="$CONF/config"
	# file exists and is symlink
	if [ -h $path ]; then
		rm $path
	fi
	ln -s "$CONF/$theme.conf" "$CONF/config"
}
