#!/bin/bash

. $(dirname $(realpath $0))/common

relink_termite fira-mono-8
pgrep termite | xargs kill -s sigusr1

alacritty="$CONF/daynight/alacritty.yml"
rm $alacritty
ln -s "$CONF/alacritty/dark.yml" $alacritty

emacsclient -e "(disable-theme 'adwaita)"
