#!/bin/bash

. $(dirname $(realpath $0))/common

relink_termite fira-mono-8
pgrep termite | xargs kill -s sigusr1

alacritty="$CONF/alacritty/daynight.yml"
rm $alacritty
ln -s "$CONF/alacritty/dark.yml" $alacritty
# force reload
touch "$(dirname $alacritty)/alacritty.yml"

emacsclient -e "(disable-theme 'adwaita)"
