# If not running interactively, don't do anything
[[ $- != *i* ]] && return

export PS1='\h [\w] \$ '

source ~/.dotfiles/bash/colors

case `hostname` in
	STATENS_laptop)
		source ~/.dotfiles/bash/STATENS_laptop.sh ;;
	arch2012|hornquist)
		source ~/.dotfiles/bash/prompt_command.sh ;;
esac

case `hostname -d` in
	lysator*) ;;
esac

shopt -s checkwinsize
shopt -s histappend
HISTCONTROL=ignoreboth
HISTSIZE=1000
HISTFILESIZE=2000

#true ${BROWSER:="/home/hugo/bin/browser"}
export EDITOR="/usr/bin/vim"
export RTV_EDITOR="/usr/bin/vim"
export RTV_URLVIEWER="/usr/bin/urlview"
export INFO_PRINT_COMMAND=">/tmp/info"
export GUILE_LOAD_PATH="/home/hugo/lib/guile"
export XDG_DOCUMENTS_DIR="$HOME/ldoc"
export XDG_DOWNLOAD_DIR="$HOME/down/other"
export XDG_PICTURES_DIR="$HOME/pic"
export LESSOPEN="|lesspipe.sh %s"
export SSH_AUTH_SOCK=/run/user/$(id -u)/ssh-agent.socket
# info path temporarly disabled due to emacs
#export INFOPATH="$HOME/info"
#export INFOPATH="$HOME/info:/usr/local/share/info/:usr/share/info/"

for path in \
	"$HOME/.local/bin" \
	"$HOME/bin" \
	"$HOME/.gem/ruby/2.3.0/bin" \
	"$HOME/.local/bin" \
	"$HOME/.cabal/bin" 
do
	if [ -d $path ]; then
		PATH="$path:$PATH"
	fi
done

[ -f ~/.dotfiles/bash/bash_aliases ] && source ~/.dotfiles/bash/bash_aliases
[ -f ~/.ghiToken ] && source ~/.ghiToken

FZF_CTRL_T_OPTS="--preview '(highlight -O ansi -l {} 2> /dev/null || cat {} || tree -C {}) 2> /dev/null | head -200'"

if [ $TERM == "xterm-termite" ]; then
	source /etc/profile.d/vte*sh
fi

if [ $(uname -s) == "Linux" ]; then
	# This shouldn't be required
	. ~/.bash_completion

	[ -f ~/.fzf.bash ] && source ~/.fzf.bash
fi
