# propper aliases

alias u="cd .."
alias uu="cd ../.."
alias uuu="cd ../../.."
alias uuuu="cd ../../../.."

alias l="ls"
alias ll="cd -"

alias todo=todo.sh
alias tmp="vim +'setlocal buftype=nofile' -n"
alias irc="env TERM=xterm ssh irc -t screen -x"
alias clip="xclip -selection clipboard"
alias wi="wiki"
alias net="watch -n1 -c nmcli -c yes"

# Creates paste. Uploads file if argument is given, STDIN otherwise.
pb() { curl -F c="@${1:--}" https://ptpb.pw?u=1; }

# aliases of questionable quality 

[ -x /usr/bin/perl-rename ] && alias rename="perl-rename"
alias eclim="eclim -command"
alias arnoldc="java -jar ~/Downloads/otherPackages/arnoldC/ArnoldC.jar -declaim"

# joke aliases
alias kitty="cat"
alias nano="echo \"Seriously? Why don't you just use Notepade.exe? Or MS Paint?\""

# enable colors if available
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
fi

sl() {
	$(which sl) $*
	ls $*
}
